export enum PermissionLabel{
    // Basic Permissions
    EDIT_OWN_ACCOUNT = "EDIT_OWN_ACCOUNT",
    DELETE_OWN_ACCOUNT = "DELETE_OWN_ACCOUNT",

    // ---- Admin permissions
    // USERS
    LIST_USERS = "LIST_USERS",
    DELETE_USERS = "DELETE_USERS",
    // GLOBAL ROLES
    SET_GLOBAL_ROLE_OF_USER = "SET_GLOBAL_ROLE_OF_USER",
    EDIT_ROLES = "EDIT_ROLES",
    LIST_ROLES = "LIST_ROLES",
    // PERMISSIONS
    EDIT_PERMISSIONS = "EDIT_PERMISSIONS",
    LIST_PERMISSIONS = "LIST_PERMISSIONS",
    // RESTAURANTS
    EDIT_RESTAURANTS = "EDIT_RESTAURANTS",
    LIST_RESTAURANTS = "LIST_RESTAURANTS",
    // EMPLOYEES
    LIST_EMPLOYEES = "LIST_EMPLOYEES",
    ADD_EMPLOYEES = 'ADD_EMPLOYEES',
    EDIT_EMPLOYEE = 'EDIT_EMPLOYEE',
    DELETE_EMPLOYEES = 'DELETE_EMPLOYEES',
    // FORMATIONS
    LIST_FORMATIONS = "LIST_FORMATIONS",
    ADD_FORMATIONS = "ADD_FORMATIONS",
    ASSIGN_FORMATIONS = "ASSIGN_FORMATIONS",
    UNASSIGN_FORMATIONS = "UNASSIGN_FORMATIONS",
    // PLANNINGS
    LIST_PLANNING = "LIST_PLANNING",
}